# This is a basic workflow to help you get started with Actions
name: backend-ci-build


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

    branches: [ "main", "hotfix/*"]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
#      - name: set up python
#        uses: actions/setup-python@v3
#        with:
#          python-version: 3.7
#          architecture: x64
#        env:
#          RUNNER_TOOL_CACHE: /hostedtoolcache

#Lets assume that Python is already there
#      - name: installing dependencies
#        run: |
#          python - m pip install
#          pip install -r requirements.txt; fi

#Remove extra stuff
#      - name: unit testing
#        run: |
#          python content_test_case.py

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.